# Documentation on all values are available here:
# https://rlaphoenix.github.io/VSMPEG

# Make sure you copy or rename this file as config.yml for vsmpeg.vpy to be able
# to find and use it. Enjoy :)

Verbose: true
Input: C:/Users/John/Videos/big-buck-bunny.mp4
MaxCacheSize: ~  # ~ = don't override, value in megabytes, e.g. 32GB: 32768

# >>> Color

ChromaLocation: ~  # ~ = Don't override

# >>> Scan

Deinterlacers:
  # These keys are function names, that will be derived from the imported object from it's
  # Environment information. This allows VSMPEG to more safely import and use the configured
  # deinterlacer functions.
  QTGMC:
    Environment:
      Import: havsfunc
    Args:
      FPSDivisor: 2
      Preset: Placebo
      MatchPreset: Placebo
      MatchPreset2: Placebo
      InputType: 0
      SourceMatch: 3
      Lossless: 2
      Sharpness: 0.2
      ShutterBlur: 0
      ShutterAngleSrc: 0
      ShutterAngleOut: 0
      SBlurLimit: 0
  VoidWeave:
    Environment:
      From: pvsfunc.pdeinterlacer
      Import: PDeinterlacer
    Args:
      color: [0, 255, 0]
      bob: false
Deinterlacer: QTGMC  # ~ = disable deinterlacing (are you sure though?)

# >>> Frame-rate

Decimation:
  Enabled: false
  Cycle: 5
  Offsets: [0, 1, 3, 4]  # empty list == uses VDecimate (not recommended: git.io/avoid-tdecimate)
  ResetCyclePerVobCell: True

# >>> Resizing and Cropping

Debox:
  Enabled: false
  Operations:
    - ["w", "4:3", 0]
    - ["h", "21:9", 0]

Crop:
  Enabled: false
  Left: 0
  Right: 0
  Top: 0
  Bottom: 0

AspectRatio:
  Value: DAR  # ~ to skip, DAR to use DAR from metadata, or e.g. 16:9 to force a specific aspect ratio
  Axis: width  # which axis to resize to get the wanted aspect ratio, width, or height
  Kernel: Spline64  # which function in core.resize do you want to use as a resize kernel?

# >>> Machine Learning and Networks

VSGAN:
  Enabled: false
  Comparer: Interleave  # ~ = Off, Interleave, StackHorizontal
  ConvertColorSpace:
    # Note: VSGAN returns the result clip in RGB, and RGB->YUV and YUV->RGB is lossy.
    #       Try not to convert color spaces at all if not needed.
    Enabled: False
    Format: YUV444P12  # can be found here: https://vapoursynth.com/doc/pythonreference.html#format-constants
  Operations:
    - enabled: false
      model: C:/Users/John/Documents/VSGAN/models/anime_upscaler/5000_G.pth
      device: 1
      chunk: false
      presample: false
      resample: 1080
    - enabled: false
      model: C:/Users/John/Documents/VSGAN/models/denoiser/2000_G.pth
      device: 1
      chunk: false
      presample: 1080
      resample: 1080
    - enabled: true
      model: C:/Users/John/Documents/VSGAN/models/inpainter/12000_G.pth
      device: 1
      chunk: false
      presample: false
      resample: false
